CREATE TABLE USERS (
ID   			INTEGER PRIMARY KEY AUTOINCREMENT,
FIRST_NAME 		VARCHAR (150),
LAST_NAME 		VARCHAR(150),
LOGIN_NAME		VARCHAR(150),
PASSWORD		VARCHAR(150),
EMAIL			VARCHAR(150),
PHONE			INTEGER,
ADDRESS			VARCHAR (300)
USER_TYPE		VARCHAR (20));

CREATE TABLE FLIGHTS (
ID 					INTEGER PRIMARY KEY AUTOINCREMENT,
FLIGHT_NUMBER		VARCHAR (100),
AIRLINE		VARCHAR (150),
FROM_AIRPORT_ID		INTEGER REFERENCES AIRPORTS(ID),
TO_AIRPORT_ID		INTEGER REFERENCES AIRPORTS(ID),
FLIGHT_DATE 		DATETIME,
DEPARTURE_TIME		DATETIME,
ARRIVING_TIME		DATETIME);

CREATE TABLE TICKETS (
ID 				INTEGER PRIMARY KEY AUTOINCREMENT,
USER_ID		    INTEGER REFERENCES USERS(ID),
FLIGHT_ID		INTEGER REFERENCES FLIGHTS(ID),
TICKET_PRICE	INTEGER);

CREATE TABLE CITIES(
ID			INTEGER PRIMARY KEY AUTOINCREMENT,
NAME		VARCHAR (200));

CREATE TABLE AIRPORTS (
ID			INTEGER PRIMARY KEY AUTOINCREMENT,
AIRPORT_NAME VARCHAR (50),
CITY_ID		INTEGER REFERENCES CITIES (ID));