CREATE TABLE USERS (
ID   			INT PRIMARY KEY,
FIRST_NAME 		VARCHAR (150),
LAST_NAME 		VARCHAR(150),
LOGIN_NAME		VARCHAR(150),
PASSWORD		VARCHAR(150),
EMAIL			VARCHAR(150),
PHONE			INT,
ADDRESS			VARCHAR (300));

CREATE TABLE FLIGHTS (
ID 					INT PRIMARY KEY,
FLIGHT_NUMBER		VARCHAR (100),
FLIGHT_NAME			VARCHAR (150),
FROM_AIRPORT_ID		INT REFERENCES AIRPORTS(ID),
TO_AIRPORT_ID		INT REFERENCES AIRPORTS(ID),
DEPARTURE_TIME		DATETIME,
ARRIVING_TIME		DATETIME,
TRAVEL_DURATION		INT);

CREATE TABLE TICKETS (
ID 				INT PRIMARY KEY,
CUSTOMER_ID		INT REFERENCES USERS(ID),
FLIGHT_ID		INT REFERENCES FLIGHTS(ID),
TICKET_PRICE	INT);

CREATE TABLE CITIES(
ID			INT PRIMARY KEY,
NAME		VARCHAR (200));

CREATE TABLE AIRPORTS (
ID			INT PRIMARY KEY,
CITY_ID		INT REFERENCES CITIES (ID));